<?php

/**
 * chenal_facebook.module
 */

/**
 * Implements hook_block_info().
 */
function chenal_facebook_block_info() {
  $blocks = array();

  $blocks['chenal_facebook'] = array(
    'info' => t('Facebook Feed'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function chenal_facebook_block_view($delta = '') {
  $block = array();

  $content = '<div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.4&appId=812209702207568";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, \'script\', \'facebook-jssdk\'));</script>';

  $content .= '<div class="fb-page" data-width="500" data-href="https://www.facebook.com/chenalvalleychurch" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true" data-show-posts="true"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/chenalvalleychurch"><a href="https://www.facebook.com/chenalvalleychurch">Chenal Valley Church</a></blockquote></div></div>';

  switch ($delta) {
    case 'chenal_facebook':
      $block['subject'] = '';
      $block['content'] = $content;
      break;
  }

  return $block;
}
